'use client';
import { useState, useEffect, useRef, Suspense } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import Layout from '@/components/Layout';
import Modal from '@/components/Modal';
import { useAuth } from '@/contexts/AuthContext';
import {
  getStockItems, createStockItem, updateStockItem, deleteStockItem, adjustStockQuantity,
  openStockUnit, finishStockUnit, updateOpenedUnitLevel,
  getStockRequests, createStockRequest, reviewStockRequest,
  notifyManagers, notifyWorker, getWorkers, getStockLogsRealtime,
  getStockCategories, addStockCategory, reverseStockLog,
} from '@/lib/firestore';
import { cn } from '@/utils/helpers';
import {
  Package, Plus, Pencil, Trash2, AlertTriangle, CheckCircle, XCircle,
  ChevronDown, ChevronUp, Minus, ClipboardList, Bell, Search, Filter, RefreshCw,
  Download, FileText, FileSpreadsheet, TrendingDown, Boxes, PackageOpen, CheckCircle2, Undo2,
} from 'lucide-react';
import toast from 'react-hot-toast';

function formatOpenedAt(iso) {
  if (!iso) return '';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return '';
  const now = new Date();
  const diffMs = now - d;
  const diffDays = Math.floor(diffMs / 86400000);
  const date = d.toLocaleDateString(undefined, { day: '2-digit', month: 'short' });
  if (diffDays <= 0) return `today (${date})`;
  if (diffDays === 1) return `yesterday (${date})`;
  if (diffDays < 7) return `${diffDays}d ago (${date})`;
  return date;
}

// ─── Export Helpers ──────────────────────────────────
function downloadCSV(items, filename = 'stock-items.csv') {
  const headers = ['Name', 'SKU', 'Category', 'Unit', 'Quantity', 'Min. Quantity', 'Status', 'Description'];
  const esc = (v) => {
    if (v == null) return '';
    const s = String(v).replace(/"/g, '""');
    return /[",\n]/.test(s) ? `"${s}"` : s;
  };
  const rows = items.map(i => {
    const status = i.minimumQuantity > 0
      ? (i.quantity === 0 ? 'Out of stock' : i.quantity < i.minimumQuantity ? 'Low stock' : 'In stock')
      : 'In stock';
    return [i.name, i.sku || '', i.category || '', i.unit || '', i.quantity, i.minimumQuantity || 0, status, i.description || ''].map(esc).join(',');
  });
  const csv = [headers.join(','), ...rows].join('\n');
  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function downloadPDF(items, orgName = 'Stock Report') {
  const date = new Date().toLocaleDateString();
  const rows = items.map(i => {
    const status = i.minimumQuantity > 0
      ? (i.quantity === 0 ? 'out' : i.quantity < i.minimumQuantity ? 'low' : 'ok')
      : 'ok';
    const statusLabel = status === 'out' ? 'Out of stock' : status === 'low' ? 'Low stock' : 'In stock';
    const statusColor = status === 'out' ? '#dc2626' : status === 'low' ? '#d97706' : '#059669';
    return `<tr>
      <td>${escapeHtml(i.name)}</td>
      <td>${escapeHtml(i.sku || '-')}</td>
      <td>${escapeHtml(i.category || '-')}</td>
      <td style="text-align:right"><strong>${i.quantity}</strong> ${escapeHtml(i.unit || '')}</td>
      <td style="text-align:right">${i.minimumQuantity || '-'}</td>
      <td><span style="color:${statusColor};font-weight:600">${statusLabel}</span></td>
    </tr>`;
  }).join('');

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${escapeHtml(orgName)} - Stock Report</title>
<style>
  body { font-family: -apple-system, Segoe UI, sans-serif; padding: 40px; color: #0f172a; }
  h1 { margin: 0 0 4px; font-size: 24px; }
  .meta { color: #64748b; font-size: 13px; margin-bottom: 24px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { text-align: left; padding: 10px 12px; background: #f8fafc; border-bottom: 2px solid #e2e8f0; font-weight: 600; }
  td { padding: 10px 12px; border-bottom: 1px solid #f1f5f9; }
  tr:nth-child(even) td { background: #fafbfc; }
  .footer { margin-top: 32px; font-size: 11px; color: #94a3b8; text-align: center; }
  @media print { body { padding: 20px; } }
</style></head><body>
  <h1>${escapeHtml(orgName)}</h1>
  <div class="meta">Stock Report · Generated ${date} · ${items.length} item${items.length !== 1 ? 's' : ''}</div>
  <table>
    <thead><tr><th>Item</th><th>SKU</th><th>Category</th><th style="text-align:right">Quantity</th><th style="text-align:right">Min.</th><th>Status</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="footer">Generated by StaffHub · staff.toolee.nl</div>
  <script>window.onload = () => { setTimeout(() => window.print(), 300); };</script>
</body></html>`;

  const w = window.open('', '_blank');
  if (!w) { toast.error('Please allow pop-ups to export PDF'); return; }
  w.document.write(html); w.document.close();
}

function escapeHtml(s) {
  return String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

const UNITS = ['pcs', 'kg', 'g', 'L', 'mL', 'box', 'pack', 'roll', 'pair', 'set'];

const STATUS_CONFIG = {
  pending:   { label: 'Pending',   color: 'bg-amber-100 text-amber-700 border-amber-200' },
  approved:  { label: 'Approved',  color: 'bg-blue-100 text-blue-700 border-blue-200' },
  rejected:  { label: 'Rejected',  color: 'bg-red-100 text-red-700 border-red-200' },
  fulfilled: { label: 'Fulfilled', color: 'bg-emerald-100 text-emerald-700 border-emerald-200' },
};

function stockStatus(item) {
  if (item.minimumQuantity > 0) {
    if (item.quantity === 0) return 'out';
    if (item.quantity < item.minimumQuantity) return 'low';
  }
  return 'ok';
}

function StockBadge({ item }) {
  const s = stockStatus(item);
  if (s === 'out') return <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-700 border border-red-200"><span className="w-1.5 h-1.5 rounded-full bg-red-500" />Out of stock</span>;
  if (s === 'low') return <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-amber-100 text-amber-700 border border-amber-200"><span className="w-1.5 h-1.5 rounded-full bg-amber-500" />Low stock</span>;
  return <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-emerald-100 text-emerald-700 border border-emerald-200"><span className="w-1.5 h-1.5 rounded-full bg-emerald-500" />In stock</span>;
}

const emptyItemForm = { name: '', description: '', category: '', unit: 'pcs', quantity: 0, minimumQuantity: 0, sku: '', bucketSize: '', bucketSizeUnit: 'kg' };
const emptyRequestForm = { itemId: '', itemName: '', quantity: 1, reason: '', urgent: false };

export default function StockPage() {
  return (
    <Suspense fallback={null}>
      <StockPageInner />
    </Suspense>
  );
}

function StockPageInner() {
  const { orgId: authOrgId, user, userProfile, isManager, isAdmin, isInventory } = useAuth();
  const searchParams = useSearchParams();
  const router = useRouter();
  const autoHandledRef = useRef(false);
  const orgIdOverride = searchParams?.get('orgId');
  const orgId = isInventory && orgIdOverride ? orgIdOverride : authOrgId;

  const [tab, setTab] = useState(() => searchParams?.get('tab') === 'requests' ? 'requests' : 'items');
  const [exportOpen, setExportOpen] = useState(false);
  const [alertModalOpen, setAlertModalOpen] = useState(false);
  const [alertRefillMap, setAlertRefillMap] = useState({});
  const [alertRefilling, setAlertRefilling] = useState(false);
  const [reversingLogId, setReversingLogId] = useState(null);

  // Open unit modal
  const [openUnitModal, setOpenUnitModal] = useState(null); // null | item
  const [openUnitForm, setOpenUnitForm] = useState({ capacity: '', levelUnit: 'g' });
  const [openingUnit, setOpeningUnit] = useState(false);

  // Level edit modal
  const [levelEditModal, setLevelEditModal] = useState(null); // null | { item, entryIdx, entry }
  const [levelEditValue, setLevelEditValue] = useState('');
  const [items, setItems] = useState([]);
  const [requests, setRequests] = useState([]);
  const [workers, setWorkers] = useState([]);
  const [logs, setLogs] = useState([]);
  const [categories, setCategories] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [categoryFilter, setCategoryFilter] = useState('all');
  const [requestStatusFilter, setRequestStatusFilter] = useState('all');
  const [logFilter, setLogFilter] = useState('all');

  // Item modal
  const [itemModal, setItemModal] = useState(null); // null | 'add' | item object (edit)
  const [itemForm, setItemForm] = useState(emptyItemForm);
  const [savingItem, setSavingItem] = useState(false);
  const [newCategory, setNewCategory] = useState('');

  // Adjust quantity modal
  const [adjustModal, setAdjustModal] = useState(null); // item object
  const [adjustQty, setAdjustQty] = useState(0);
  const [adjustMode, setAdjustMode] = useState('set'); // 'set' | 'add' | 'subtract'
  const [savingAdjust, setSavingAdjust] = useState(false);

  // Request modal (worker creates request)
  const [requestModal, setRequestModal] = useState(false);
  const [requestForm, setRequestForm] = useState(emptyRequestForm);
  const [savingRequest, setSavingRequest] = useState(false);

  // Review modal (manager reviews request)
  const [reviewModal, setReviewModal] = useState(null); // request object
  const [reviewNotes, setReviewNotes] = useState('');
  const [savingReview, setSavingReview] = useState(false);

  // Delete confirm
  const [deleteConfirm, setDeleteConfirm] = useState(null); // item object

  const canManage = isAdmin || isManager || isInventory;

  const handleOpenUnit = (item) => {
    setOpenUnitForm({ capacity: '', levelUnit: 'g' });
    setOpenUnitModal(item);
  };

  const confirmOpenUnit = async () => {
    if (!openUnitModal) return;
    setOpeningUnit(true);
    try {
      await openStockUnit(
        openUnitModal.id,
        { uid: user?.uid, displayName: userProfile?.displayName || userProfile?.name || '' },
        { capacity: Number(openUnitForm.capacity) || 0, levelUnit: openUnitForm.levelUnit }
      );
      toast.success(`Opened 1 ${openUnitModal.unit || 'unit'} of ${openUnitModal.name}`);
      setOpenUnitModal(null);
      await load();
    } catch (e) {
      toast.error(e.message || 'Failed to open unit');
    } finally {
      setOpeningUnit(false);
    }
  };

  const handleLevelEdit = (item, entryIdx, entry) => {
    setLevelEditValue(String(entry.currentLevel ?? entry.capacity ?? ''));
    setLevelEditModal({ item, entryIdx, entry });
  };

  const saveLevelEdit = async () => {
    if (!levelEditModal) return;
    try {
      await updateOpenedUnitLevel(levelEditModal.item.id, levelEditModal.entryIdx, Number(levelEditValue) || 0);
      toast.success('Level updated');
      setLevelEditModal(null);
      await load();
    } catch {
      toast.error('Failed to update level');
    }
  };

  const handleFinishUnit = async (item) => {
    try {
      await finishStockUnit(item.id, { uid: user?.uid, displayName: userProfile?.displayName || userProfile?.name || '' });
      toast.success(`Finished 1 ${item.unit || 'unit'} of ${item.name}`);
      await load();
    } catch (e) {
      toast.error(e.message || 'Failed to finish unit');
    }
  };

  const openAlertModal = () => {
    const missing = items.filter(i => stockStatus(i) !== 'ok');
    const map = {};
    missing.forEach(i => { map[i.id] = 0; });
    setAlertRefillMap(map);
    setAlertModalOpen(true);
  };

  const handleAlertRefillAll = async () => {
    setAlertRefilling(true);
    try {
      const updates = Object.entries(alertRefillMap)
        .map(([id, add]) => ({ id, add: Number(add) || 0 }))
        .filter(({ add }) => add > 0);
      for (const { id, add } of updates) {
        const item = items.find(x => x.id === id);
        if (!item) continue;
        await updateStockItem(id, { quantity: (item.quantity || 0) + add });
      }
      toast.success(`Refilled ${updates.length} item${updates.length !== 1 ? 's' : ''}`);
      await load();
      setAlertModalOpen(false);
    } catch (e) {
      toast.error('Failed to refill stock');
    } finally {
      setAlertRefilling(false);
    }
  };

  const load = async () => {
    if (!orgId) return;
    setLoading(true);
    try {
      const [itemsData, requestsData, workersData, categoriesData] = await Promise.all([
        getStockItems({ orgId }),
        getStockRequests({ orgId }),
        canManage ? getWorkers({ orgId }) : Promise.resolve([]),
        getStockCategories(orgId),
      ]);
      setItems(itemsData);
      setRequests(requestsData);
      setWorkers(workersData);
      setCategories(categoriesData);
    } catch (e) {
      toast.error('Failed to load stock data');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, [orgId]);

  // Auto-create requests for out-of-stock items when coming from dashboard banner
  useEffect(() => {
    if (autoHandledRef.current) return;
    if (searchParams?.get('auto') !== '1') return;
    if (!orgId || !user || loading) return;
    if (items.length === 0) return;
    autoHandledRef.current = true;

    const outItems = items.filter(i => stockStatus(i) === 'out');
    if (outItems.length === 0) {
      toast.success('No out-of-stock items to request');
      router.replace('/stock?tab=requests');
      return;
    }
    const existingItemIds = new Set(
      requests.filter(r => r.status === 'pending' && r.itemId).map(r => r.itemId)
    );
    const toCreate = outItems.filter(i => !existingItemIds.has(i.id));
    if (toCreate.length === 0) {
      toast('Pending requests already exist for all out-of-stock items', { icon: 'ℹ️' });
      router.replace('/stock?tab=requests');
      return;
    }
    (async () => {
      try {
        for (const item of toCreate) {
          const data = {
            orgId,
            itemId: item.id,
            itemName: item.name,
            quantity: Math.max(1, (item.minimumQuantity || 1) * 2),
            reason: 'Auto-generated: item is out of stock',
            urgent: true,
            requestedBy: user.uid,
            requestedByName: userProfile?.displayName || '',
            requestedByRole: userProfile?.role || 'manager',
            workerId: userProfile?.workerId || null,
          };
          await createStockRequest(data);
        }
        toast.success(`Created ${toCreate.length} urgent request(s)`);
        router.replace('/stock?tab=requests');
        load();
      } catch {
        toast.error('Failed to create requests');
      }
    })();
  }, [searchParams, orgId, user, loading, items, requests]);

  useEffect(() => {
    if (!orgId || !canManage) return;
    const unsubscribe = getStockLogsRealtime(orgId, setLogs);
    return () => unsubscribe();
  }, [orgId, canManage]);

  // ─── Derived data ────────────────────────────────────
  const handleReverseLog = async (log) => {
    if (log.reversed || log.type === 'reversed' || log.type === 'created' || log.type === 'deleted') return;
    setReversingLogId(log.id);
    try {
      await reverseStockLog(log.id, userProfile);
      toast.success('Action reversed');
      await load();
    } catch (e) {
      toast.error(e.message || 'Failed to reverse');
    } finally {
      setReversingLogId(null);
    }
  };

  const alertItems = items.filter(i => stockStatus(i) === 'low' || stockStatus(i) === 'out');
  const myRequests = requests.filter(r => r.requestedBy === user?.uid);
  const pendingRequests = requests.filter(r => r.status === 'pending');

  const filteredItems = items.filter(i => {
    const matchSearch = !search || i.name.toLowerCase().includes(search.toLowerCase()) || (i.sku || '').toLowerCase().includes(search.toLowerCase());
    const matchCat = categoryFilter === 'all' || i.category === categoryFilter;
    return matchSearch && matchCat;
  });

  const filteredRequests = (canManage ? requests : myRequests).filter(r =>
    requestStatusFilter === 'all' || r.status === requestStatusFilter
  );

  const workerName = (id) => {
    const w = workers.find(x => x.userId === id || x.id === id);
    return w ? `${w.firstName} ${w.lastName}` : (userProfile?.displayName || 'Unknown');
  };

  // ─── Item CRUD ───────────────────────────────────────
  const addCategory = async () => {
    if (!newCategory.trim()) return;
    const trimmed = newCategory.trim();
    if (categories.includes(trimmed)) {
      toast.error('Category already exists');
      return;
    }
    try {
      await addStockCategory(orgId, trimmed);
      setCategories([...categories, trimmed]);
      setItemForm(f => ({ ...f, category: trimmed }));
      setNewCategory('');
      toast.success('Category added');
    } catch {
      toast.error('Failed to add category');
    }
  };

  const openAddItem = () => {
    setItemForm(emptyItemForm);
    setNewCategory('');
    setItemModal('add');
  };

  const openEditItem = (item) => {
    setItemForm({ name: item.name, description: item.description || '', category: item.category || '', unit: item.unit || 'pcs', quantity: item.quantity, minimumQuantity: item.minimumQuantity || 0, sku: item.sku || '', bucketSize: item.bucketSize || '', bucketSizeUnit: item.bucketSizeUnit || 'kg' });
    setNewCategory('');
    setItemModal(item);
  };

  const saveItem = async () => {
    if (!itemForm.name.trim()) return toast.error('Item name is required');
    setSavingItem(true);
    try {
      const data = {
        orgId,
        name: itemForm.name.trim(),
        description: itemForm.description.trim(),
        category: itemForm.category,
        unit: itemForm.unit,
        quantity: Number(itemForm.quantity) || 0,
        minimumQuantity: Number(itemForm.minimumQuantity) || 0,
        sku: itemForm.sku.trim(),
        bucketSize: itemForm.bucketSize ? Number(itemForm.bucketSize) : null,
        bucketSizeUnit: itemForm.bucketSizeUnit || 'kg',
        createdBy: user?.uid,
        createdByName: userProfile?.displayName || '',
      };
      if (itemModal === 'add') {
        await createStockItem(data, userProfile);
        toast.success('Item added');
      } else {
        await updateStockItem(itemModal.id, { name: data.name, description: data.description, category: data.category, unit: data.unit, quantity: data.quantity, minimumQuantity: data.minimumQuantity, sku: data.sku, bucketSize: data.bucketSize, bucketSizeUnit: data.bucketSizeUnit }, userProfile);
        toast.success('Item updated');
      }
      setItemModal(null);
      load();
    } catch {
      toast.error('Failed to save item');
    } finally {
      setSavingItem(false);
    }
  };

  const confirmDelete = async () => {
    if (!deleteConfirm) return;
    try {
      await deleteStockItem(deleteConfirm.id, userProfile);
      toast.success('Item removed');
      setDeleteConfirm(null);
      load();
    } catch {
      toast.error('Failed to delete item');
    }
  };

  // ─── Adjust Quantity ─────────────────────────────────
  const openAdjust = (item) => {
    setAdjustModal(item);
    setAdjustQty(item.quantity);
    setAdjustMode(canManage ? 'set' : 'subtract');
  };

  const saveAdjust = async () => {
    if (!adjustModal) return;
    setSavingAdjust(true);
    try {
      let newQty;
      if (adjustMode === 'set') newQty = Number(adjustQty);
      else if (adjustMode === 'add') newQty = adjustModal.quantity + Number(adjustQty);
      else newQty = Math.max(0, adjustModal.quantity - Number(adjustQty));

      await adjustStockQuantity(adjustModal.id, newQty, userProfile);
      toast.success('Stock updated');
      setAdjustModal(null);
      load();
    } catch {
      toast.error('Failed to update stock');
    } finally {
      setSavingAdjust(false);
    }
  };

  // ─── Stock Requests ──────────────────────────────────
  const openRequest = (item = null) => {
    setRequestForm(item
      ? { itemId: item.id, itemName: item.name, quantity: 1, reason: '', urgent: stockStatus(item) !== 'ok' }
      : emptyRequestForm
    );
    setRequestModal(true);
  };

  const submitRequest = async () => {
    if (!requestForm.itemName.trim()) return toast.error('Please specify an item');
    if (!requestForm.reason.trim()) return toast.error('Please provide a reason');
    setSavingRequest(true);
    try {
      const data = {
        orgId,
        itemId: requestForm.itemId || null,
        itemName: requestForm.itemName.trim(),
        quantity: Number(requestForm.quantity) || 1,
        reason: requestForm.reason.trim(),
        urgent: requestForm.urgent,
        requestedBy: user?.uid,
        requestedByName: userProfile?.displayName || '',
        requestedByRole: userProfile?.role || 'worker',
        workerId: userProfile?.workerId || null,
      };
      await createStockRequest(data);
      await notifyManagers(orgId, {
        type: 'stock_request',
        title: `Stock Request: ${data.itemName}`,
        message: `${data.requestedByName} requested ${data.quantity} ${data.itemName}${data.urgent ? ' (URGENT)' : ''}: ${data.reason}`,
        link: '/stock',
      });
      toast.success('Request submitted');
      setRequestModal(false);
      load();
    } catch {
      toast.error('Failed to submit request');
    } finally {
      setSavingRequest(false);
    }
  };

  const handleReview = async (status) => {
    if (!reviewModal) return;
    setSavingReview(true);
    try {
      await reviewStockRequest(reviewModal.id, status, userProfile?.displayName || user?.uid, reviewNotes);
      // Notify the requester
      if (reviewModal.workerId) {
        await notifyWorker(reviewModal.workerId, orgId, {
          type: 'stock_request_response',
          title: `Stock Request ${status === 'approved' ? 'Approved' : status === 'rejected' ? 'Rejected' : 'Fulfilled'}`,
          message: `Your request for ${reviewModal.itemName} has been ${status}${reviewNotes ? `: ${reviewNotes}` : '.'}`,
          link: '/stock',
        });
      }
      toast.success(`Request ${status}`);
      setReviewModal(null);
      setReviewNotes('');
      load();
    } catch {
      toast.error('Failed to update request');
    } finally {
      setSavingReview(false);
    }
  };

  if (loading) {
    return (
      <Layout>
        <div className="flex items-center justify-center h-64">
          <RefreshCw className="w-6 h-6 animate-spin text-brand-500" />
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
          <div className="min-w-0">
            <h1 className="page-title">Stock Management</h1>
            <p className="text-sm text-surface-500 mt-0.5">
              {canManage ? 'Manage inventory, track stock changes, and review requests' : 'Track stock levels, update quantities, and request items'}
            </p>
          </div>
          <div className="flex items-center gap-2 flex-wrap">
            <button onClick={load} className="btn-ghost p-2 rounded-lg" title="Refresh">
              <RefreshCw className="w-4 h-4" />
            </button>
            {canManage && (
            <div className="relative">
              <button
                onClick={() => setExportOpen(v => !v)}
                disabled={items.length === 0}
                className="btn-secondary flex items-center gap-2 disabled:opacity-50"
                title="Export stock data"
              >
                <Download className="w-4 h-4" /> <span className="hidden sm:inline">Export</span>
                <ChevronDown className="w-3.5 h-3.5" />
              </button>
              {exportOpen && (
                <>
                  <div className="fixed inset-0 z-10" onClick={() => setExportOpen(false)} />
                  <div className="absolute right-0 mt-1 w-48 bg-white rounded-lg shadow-lg border border-surface-200 py-1 z-20">
                    <button
                      onClick={() => { downloadCSV(filteredItems); setExportOpen(false); }}
                      className="w-full px-3 py-2 text-sm text-left hover:bg-surface-50 flex items-center gap-2"
                    >
                      <FileSpreadsheet className="w-4 h-4 text-emerald-600" /> Download CSV
                    </button>
                    <button
                      onClick={() => { downloadPDF(filteredItems, userProfile?.organizationName || 'Stock Report'); setExportOpen(false); }}
                      className="w-full px-3 py-2 text-sm text-left hover:bg-surface-50 flex items-center gap-2"
                    >
                      <FileText className="w-4 h-4 text-red-500" /> Download PDF
                    </button>
                  </div>
                </>
              )}
            </div>
            )}
            {canManage && (
              <button onClick={openAddItem} className="btn-primary flex items-center gap-2">
                <Plus className="w-4 h-4" /> <span className="hidden sm:inline">Add Item</span><span className="sm:hidden">Add</span>
              </button>
            )}
            {!canManage && (
              <>
                <button onClick={openAddItem} className="btn-primary flex items-center gap-2">
                  <Plus className="w-4 h-4" /> Add
                </button>
                <button onClick={() => openRequest()} className="btn-secondary flex items-center gap-2">
                  <ClipboardList className="w-4 h-4" /> <span className="hidden sm:inline">Request</span>
                </button>
              </>
            )}
          </div>
        </div>

        {/* Stats row */}
        <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
          <div className="card p-3 sm:p-4">
            <div className="flex items-center gap-2 text-xs text-surface-500 font-medium"><Boxes className="w-3.5 h-3.5" />Total items</div>
            <p className="text-xl sm:text-2xl font-bold text-surface-900 mt-1">{items.length}</p>
          </div>
          <div className="card p-3 sm:p-4">
            <div className="flex items-center gap-2 text-xs text-sky-600 font-medium"><PackageOpen className="w-3.5 h-3.5" />In use</div>
            <p className="text-xl sm:text-2xl font-bold text-sky-600 mt-1">{items.reduce((n, i) => n + (i.inUseQuantity || 0), 0)}</p>
          </div>
          <div className="card p-3 sm:p-4">
            <div className="flex items-center gap-2 text-xs text-amber-600 font-medium"><TrendingDown className="w-3.5 h-3.5" />Low stock</div>
            <p className="text-xl sm:text-2xl font-bold text-amber-600 mt-1">{items.filter(i => stockStatus(i) === 'low').length}</p>
          </div>
          <div className="card p-3 sm:p-4">
            <div className="flex items-center gap-2 text-xs text-red-600 font-medium"><AlertTriangle className="w-3.5 h-3.5" />Out of stock</div>
            <p className="text-xl sm:text-2xl font-bold text-red-600 mt-1">{items.filter(i => stockStatus(i) === 'out').length}</p>
          </div>
          <div className="card p-3 sm:p-4">
            <div className="flex items-center gap-2 text-xs text-blue-600 font-medium"><ClipboardList className="w-3.5 h-3.5" />Pending requests</div>
            <p className="text-xl sm:text-2xl font-bold text-blue-600 mt-1">{pendingRequests.length}</p>
          </div>
        </div>

        {/* Alert banner — low/out of stock items */}
        {alertItems.length > 0 && (
          <button
            type="button"
            onClick={openAlertModal}
            className="w-full text-left rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 flex items-start gap-3 hover:bg-amber-100/70 transition-colors active:scale-[0.995]"
          >
            <AlertTriangle className="w-5 h-5 text-amber-500 flex-shrink-0 mt-0.5" />
            <div className="flex-1 min-w-0">
              <p className="text-sm font-semibold text-amber-800">
                {alertItems.filter(i => stockStatus(i) === 'out').length > 0
                  ? `${alertItems.filter(i => stockStatus(i) === 'out').length} item(s) out of stock · `
                  : ''}
                {alertItems.filter(i => stockStatus(i) === 'low').length > 0
                  ? `${alertItems.filter(i => stockStatus(i) === 'low').length} item(s) below minimum`
                  : ''}
              </p>
              <p className="text-xs text-amber-700 mt-0.5 truncate">
                {alertItems.map(i => i.name).join(', ')}
              </p>
            </div>
            <span className="text-xs font-semibold text-amber-800 bg-white border border-amber-200 px-2.5 py-1 rounded-lg flex-shrink-0">
              {canManage ? 'Review & refill' : 'View'}
            </span>
          </button>
        )}

        <Modal open={alertModalOpen} onClose={() => setAlertModalOpen(false)} title="Missing stock items" size="lg">
          {alertItems.length === 0 ? (
            <p className="text-sm text-surface-500">All items are well stocked.</p>
          ) : (
            <div className="space-y-3">
              <p className="text-xs text-surface-500">
                {canManage
                  ? 'Suggested amounts bring each item to 2× its minimum. Adjust as needed, then refill all at once.'
                  : 'Items below or at their minimum level. Ask a manager to restock or create a request.'}
              </p>
              <div className="space-y-2 max-h-[55vh] overflow-y-auto pr-1">
                {alertItems.map(item => {
                  const s = stockStatus(item);
                  const isOut = s === 'out';
                  return (
                    <div key={item.id} className="flex items-center gap-3 p-3 rounded-xl border border-surface-200 bg-white">
                      <div className={cn('w-9 h-9 rounded-lg flex items-center justify-center flex-shrink-0', isOut ? 'bg-red-100 text-red-600' : 'bg-amber-100 text-amber-600')}>
                        <Package className="w-4 h-4" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-semibold text-surface-900 truncate">{item.name}</p>
                        <p className="text-xs text-surface-500">
                          {item.quantity} / min {item.minimumQuantity} {item.unit || ''}
                          <span className={cn('ml-2 px-1.5 py-0.5 rounded text-[10px] font-semibold', isOut ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700')}>
                            {isOut ? 'OUT' : 'LOW'}
                          </span>
                        </p>
                      </div>
                      {canManage ? (
                        <div className="flex items-center gap-1.5 flex-shrink-0">
                          <span className="text-xs text-surface-500">+</span>
                          <input
                            type="number"
                            min="0"
                            value={alertRefillMap[item.id] ?? ''}
                            onChange={e => setAlertRefillMap(m => ({ ...m, [item.id]: e.target.value }))}
                            className="w-16 px-2 py-1.5 text-sm border border-surface-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-500"
                          />
                          <span className="text-xs text-surface-500">{item.unit || ''}</span>
                        </div>
                      ) : (
                        <button
                          onClick={() => { setAlertModalOpen(false); openRequest(item); }}
                          className="text-xs font-semibold px-3 py-1.5 rounded-lg bg-brand-50 text-brand-700 border border-brand-200 hover:bg-brand-100 flex-shrink-0"
                        >
                          Request
                        </button>
                      )}
                    </div>
                  );
                })}
              </div>
              {canManage && (
                <div className="flex gap-2 pt-2 border-t border-surface-100">
                  <button onClick={() => setAlertModalOpen(false)} className="btn-secondary flex-1">Cancel</button>
                  <button onClick={handleAlertRefillAll} disabled={alertRefilling} className="btn-primary flex-1 flex items-center justify-center gap-2">
                    {alertRefilling ? 'Refilling…' : 'Refill all'}
                  </button>
                </div>
              )}
            </div>
          )}
        </Modal>

        {/* Tabs */}
        <div className="flex gap-1 border-b border-surface-200 overflow-x-auto -mx-4 px-4 sm:mx-0 sm:px-0">
          {[
            { id: 'items', label: 'Items', count: items.length },
            { id: 'requests', label: canManage ? 'Requests' : 'My Requests', count: canManage ? pendingRequests.length : myRequests.filter(r => r.status === 'pending').length },
            ...(canManage ? [{ id: 'logs', label: 'Activity', count: 0 }] : []),
          ].map(t => (
            <button
              key={t.id}
              onClick={() => setTab(t.id)}
              className={cn(
                'px-4 py-2.5 text-sm font-medium border-b-2 transition-colors flex items-center gap-2',
                tab === t.id
                  ? 'border-brand-500 text-brand-600'
                  : 'border-transparent text-surface-500 hover:text-surface-700'
              )}
            >
              {t.label}
              {t.count > 0 && (
                <span className={cn('rounded-full px-1.5 py-0.5 text-xs font-semibold', tab === t.id ? 'bg-brand-100 text-brand-700' : 'bg-surface-100 text-surface-600')}>
                  {t.count}
                </span>
              )}
            </button>
          ))}
        </div>

        {/* ── Items Tab ── */}
        {tab === 'items' && (
          <div className="space-y-4">
            {/* Filters */}
            <div className="flex flex-col sm:flex-row gap-3">
              <div className="relative flex-1">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-surface-400" />
                <input
                  className="input-field pl-9 w-full"
                  placeholder="Search items or SKU..."
                  value={search}
                  onChange={e => setSearch(e.target.value)}
                />
              </div>
              <select className="select-field sm:w-48" value={categoryFilter} onChange={e => setCategoryFilter(e.target.value)}>
                <option value="all">All categories</option>
                {categories.map(c => <option key={c} value={c}>{c}</option>)}
              </select>
            </div>

            {filteredItems.length === 0 ? (
              <div className="card text-center py-16">
                <Package className="w-10 h-10 text-surface-300 mx-auto mb-3" />
                <p className="text-surface-500 font-medium">{items.length === 0 ? 'No stock items yet' : 'No items match your filters'}</p>
                {items.length === 0 && (
                  <button onClick={openAddItem} className="btn-primary mt-4 inline-flex items-center gap-2">
                    <Plus className="w-4 h-4" /> Add your first item
                  </button>
                )}
              </div>
            ) : (
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                {filteredItems.map(item => {
                  const s = stockStatus(item);
                  return (
                    <div key={item.id} className={cn('card p-4 flex flex-col gap-3', s === 'out' && 'border-red-200 bg-red-50/30', s === 'low' && 'border-amber-200 bg-amber-50/20')}>
                      <div className="flex items-start justify-between gap-2">
                        <div className="min-w-0">
                          <p className="font-semibold text-surface-900 truncate">{item.name}</p>
                          {item.sku && <p className="text-xs text-surface-400 mt-0.5">SKU: {item.sku}</p>}
                        </div>
                        <span className="text-xs px-2 py-0.5 rounded-full bg-surface-100 text-surface-600 whitespace-nowrap flex-shrink-0">{item.category || 'Other'}</span>
                      </div>

                      {item.description && <p className="text-sm text-surface-500 line-clamp-2">{item.description}</p>}

                      <div className="flex items-center justify-between">
                        <div>
                          <p className="text-2xl font-bold text-surface-900">{item.quantity} <span className="text-sm font-normal text-surface-500">{item.unit}</span></p>
                          {item.minimumQuantity > 0 && (
                            <p className="text-xs text-surface-400">Min: {item.minimumQuantity} {item.unit}</p>
                          )}
                        </div>
                        <StockBadge item={item} />
                      </div>

                      {(item.inUseQuantity || 0) > 0 && (
                        <div className="px-2.5 py-2 rounded-lg bg-sky-50 border border-sky-200 text-sky-700 space-y-2">
                          <div className="flex items-center gap-2">
                            <PackageOpen className="w-3.5 h-3.5 flex-shrink-0" />
                            <span className="text-xs font-semibold">{item.inUseQuantity} in use</span>
                            <button
                              onClick={() => handleFinishUnit(item)}
                              className="ml-auto text-[11px] font-semibold px-2 py-0.5 rounded bg-white border border-sky-200 hover:bg-sky-100 flex items-center gap-1"
                              title="Finish oldest opened unit"
                            >
                              <CheckCircle2 className="w-3 h-3" /> Finish
                            </button>
                          </div>
                          {Array.isArray(item.inUseOpenedAt) && item.inUseOpenedAt.length > 0 && (
                            <div className="space-y-1.5">
                              {item.inUseOpenedAt.map((entry, idx) => {
                                const hasCap = entry.capacity > 0;
                                const pct = hasCap ? Math.min(100, Math.max(0, ((entry.currentLevel || 0) / entry.capacity) * 100)) : null;
                                const levelColor = pct !== null ? (pct < 15 ? 'bg-red-500' : pct < 40 ? 'bg-amber-500' : 'bg-sky-500') : '';
                                return (
                                  <button
                                    key={idx}
                                    type="button"
                                    onClick={() => handleLevelEdit(item, idx, entry)}
                                    className="w-full text-left rounded-md bg-white/70 border border-sky-100 px-2 py-1.5 hover:bg-white transition-colors"
                                  >
                                    <div className="flex items-center justify-between text-[10px]">
                                      <span className="text-sky-600">
                                        #{idx + 1} · {formatOpenedAt(entry.at)}
                                        {entry.byName ? ` · ${entry.byName}` : ''}
                                      </span>
                                      {hasCap && (
                                        <span className="font-bold text-sky-800">
                                          {entry.currentLevel ?? 0}/{entry.capacity} {entry.levelUnit || ''}
                                        </span>
                                      )}
                                    </div>
                                    {hasCap && (
                                      <div className="h-1.5 rounded-full bg-sky-100 overflow-hidden mt-1">
                                        <div className={cn('h-full rounded-full transition-all', levelColor)} style={{ width: `${pct}%` }} />
                                      </div>
                                    )}
                                  </button>
                                );
                              })}
                            </div>
                          )}
                        </div>
                      )}

                      {/* Stock bar */}
                      {item.minimumQuantity > 0 && (
                        <div className="h-1.5 rounded-full bg-surface-100 overflow-hidden">
                          <div
                            className={cn('h-full rounded-full transition-all', s === 'out' ? 'bg-red-500' : s === 'low' ? 'bg-amber-500' : 'bg-emerald-500')}
                            style={{ width: `${Math.min(100, (item.quantity / (item.minimumQuantity * 2)) * 100)}%` }}
                          />
                        </div>
                      )}

                      <div className="flex items-center gap-2 pt-1">
                        <button
                          onClick={() => handleOpenUnit(item)}
                          disabled={(item.quantity || 0) <= 0}
                          className="btn-secondary text-xs px-3 py-1.5 flex items-center justify-center gap-1.5 disabled:opacity-40 disabled:cursor-not-allowed"
                          title="Open a unit (move from stock to in use)"
                        >
                          <PackageOpen className="w-3.5 h-3.5" /> Open
                        </button>
                        <button onClick={() => openAdjust(item)} className="btn-secondary text-xs px-3 py-1.5 flex-1 flex items-center justify-center gap-1.5">
                          <RefreshCw className="w-3.5 h-3.5" /> Update
                        </button>
                        {canManage && (
                          <>
                            <button onClick={() => openEditItem(item)} className="btn-icon" title="Edit item">
                              <Pencil className="w-4 h-4" />
                            </button>
                            <button onClick={() => setDeleteConfirm(item)} className="btn-icon text-red-500 hover:bg-red-50" title="Delete item">
                              <Trash2 className="w-4 h-4" />
                            </button>
                          </>
                        )}
                        {!canManage && (
                          <button onClick={() => openRequest(item)} className="btn-icon" title="Request item">
                            <ClipboardList className="w-4 h-4" />
                          </button>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        )}

        {/* ── Requests Tab ── */}
        {tab === 'requests' && (
          <div className="space-y-4">
            <div className="flex items-center justify-between gap-3">
              <select className="select-field w-44" value={requestStatusFilter} onChange={e => setRequestStatusFilter(e.target.value)}>
                <option value="all">All statuses</option>
                <option value="pending">Pending</option>
                <option value="approved">Approved</option>
                <option value="rejected">Rejected</option>
                <option value="fulfilled">Fulfilled</option>
              </select>
              {!canManage && (
                <button onClick={() => openRequest()} className="btn-primary flex items-center gap-2">
                  <Plus className="w-4 h-4" /> New Request
                </button>
              )}
            </div>

            {filteredRequests.length === 0 ? (
              <div className="card text-center py-16">
                <ClipboardList className="w-10 h-10 text-surface-300 mx-auto mb-3" />
                <p className="text-surface-500 font-medium">No requests found</p>
                {!canManage && (
                  <button onClick={() => openRequest()} className="btn-primary mt-4 inline-flex items-center gap-2">
                    <Plus className="w-4 h-4" /> Submit a request
                  </button>
                )}
              </div>
            ) : (
              <div className="space-y-3">
                {filteredRequests.map(req => (
                  <div key={req.id} className={cn('card p-4', req.urgent && req.status === 'pending' && 'border-orange-200 bg-orange-50/20')}>
                    <div className="flex items-start justify-between gap-3">
                      <div className="min-w-0 flex-1">
                        <div className="flex items-center gap-2 flex-wrap">
                          <p className="font-semibold text-surface-900">{req.itemName}</p>
                          {req.urgent && <span className="text-xs px-1.5 py-0.5 rounded bg-orange-100 text-orange-700 font-medium">URGENT</span>}
                          <span className={cn('text-xs px-2 py-0.5 rounded-full border font-medium', STATUS_CONFIG[req.status]?.color)}>
                            {STATUS_CONFIG[req.status]?.label}
                          </span>
                        </div>
                        <p className="text-sm text-surface-500 mt-1">
                          Qty: <strong>{req.quantity}</strong> · {canManage ? `By: ${req.requestedByName}` : ''} · {new Date(req.createdAt).toLocaleDateString()}
                        </p>
                        <p className="text-sm text-surface-600 mt-1">"{req.reason}"</p>
                        {req.adminNotes && (
                          <p className="text-sm text-surface-500 mt-1 italic">Note: {req.adminNotes}</p>
                        )}
                      </div>
                      {canManage && req.status === 'pending' && (
                        <button
                          onClick={() => { setReviewModal(req); setReviewNotes(''); }}
                          className="btn-secondary text-xs px-3 py-1.5 flex-shrink-0"
                        >
                          Review
                        </button>
                      )}
                      {canManage && req.status === 'approved' && (
                        <button
                          onClick={() => { setReviewModal(req); setReviewNotes(''); }}
                          className="btn-secondary text-xs px-3 py-1.5 flex-shrink-0 text-emerald-600 border-emerald-200 hover:bg-emerald-50"
                        >
                          Mark Fulfilled
                        </button>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* ── Activity Tab ── */}
        {tab === 'logs' && canManage && (
          <div className="space-y-4">
            <div className="flex items-center justify-between gap-3">
              <select className="select-field w-44" value={logFilter} onChange={e => setLogFilter(e.target.value)}>
                <option value="all">All actions</option>
                <option value="add">Added stock</option>
                <option value="remove">Removed stock</option>
                <option value="edited">Edited</option>
                <option value="created">Created</option>
                <option value="deleted">Deleted</option>
                <option value="recipe_used">Recipe used</option>
                <option value="reversed">Reversed</option>
              </select>
              <span className="text-xs text-surface-400">Updates in real-time</span>
            </div>

            {logs.length === 0 ? (
              <div className="card text-center py-16">
                <RefreshCw className="w-10 h-10 text-surface-300 mx-auto mb-3" />
                <p className="text-surface-500 font-medium">No activity recorded yet</p>
                <p className="text-sm text-surface-400 mt-1">Stock changes will appear here</p>
              </div>
            ) : (
              <div className="space-y-2">
                {(logFilter === 'all' ? logs : logs.filter(l => l.type === logFilter)).map(log => {
                  const canReverse = !log.reversed && log.type !== 'reversed' && log.type !== 'created' && log.type !== 'deleted';
                  return (
                  <div key={log.id} className={cn('card p-4', log.reversed && 'opacity-50')}>
                    <div className="flex items-start justify-between gap-3">
                      <div className="flex items-center gap-3 flex-1">
                        <div className={cn(
                          'w-9 h-9 rounded-full flex items-center justify-center flex-shrink-0',
                          log.type === 'add' ? 'bg-emerald-100 text-emerald-600' :
                          log.type === 'remove' ? 'bg-red-100 text-red-600' :
                          log.type === 'edited' ? 'bg-blue-100 text-blue-600' :
                          log.type === 'created' ? 'bg-purple-100 text-purple-600' :
                          log.type === 'reversed' ? 'bg-orange-100 text-orange-600' :
                          log.type === 'recipe_used' ? 'bg-pink-100 text-pink-600' :
                          'bg-gray-100 text-gray-600'
                        )}>
                          {log.type === 'add' ? '+' : log.type === 'remove' ? '−' : log.type === 'edited' ? '✎' : log.type === 'created' ? '★' : log.type === 'reversed' ? '↩' : log.type === 'recipe_used' ? '🍳' : '×'}
                        </div>
                        <div className="min-w-0 flex-1">
                          <p className="font-medium text-surface-900">
                            <span className="truncate">{log.itemName}</span>
                            <span className={cn(
                              'ml-2 text-sm font-semibold',
                              log.change > 0 ? 'text-emerald-600' : log.change < 0 ? 'text-red-600' : 'text-surface-500'
                            )}>
                              {log.change > 0 ? `+${log.change}` : log.change}
                            </span>
                            {log.reversed && <span className="ml-2 text-[10px] font-semibold text-orange-600 bg-orange-100 px-1.5 py-0.5 rounded">REVERSED</span>}
                          </p>
                          <p className="text-xs text-surface-500">
                            {log.type === 'add' ? 'Added stock' : log.type === 'remove' ? 'Removed stock' : log.type === 'edited' ? 'Edited item' : log.type === 'created' ? 'Created item' : log.type === 'reversed' ? 'Reversed action' : log.type === 'recipe_used' ? 'Recipe used' : 'Deleted item'}
                            {' · '}{log.updatedByName || 'Unknown'}
                            {' · '}{log.createdAt ? new Date(log.createdAt).toLocaleString() : 'Just now'}
                          </p>
                          {log.previousQuantity !== undefined && (
                            <p className="text-xs text-surface-400">
                              {log.previousQuantity} → {log.newQuantity}
                            </p>
                          )}
                          {log.details && <p className="text-xs text-surface-400 italic">{log.details}</p>}
                        </div>
                      </div>
                      {canReverse && (
                        <button
                          onClick={() => handleReverseLog(log)}
                          disabled={reversingLogId === log.id}
                          title="Reverse this action"
                          className="flex-shrink-0 p-2 rounded-lg text-surface-400 hover:text-orange-600 hover:bg-orange-50 transition-colors disabled:opacity-50"
                        >
                          <Undo2 className="w-4 h-4" />
                        </button>
                      )}
                    </div>
                  </div>
                  );
                })}
              </div>
            )}
          </div>
        )}
      </div>

      {/* ── Add / Edit Item Modal ── */}
      {itemModal !== null && (
        <Modal open={true} onClose={() => setItemModal(null)} title={itemModal === 'add' ? 'Add Stock Item' : 'Edit Stock Item'}>
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="col-span-2">
                <label className="block text-sm font-medium text-surface-700 mb-1">Item Name *</label>
                <input className="input-field w-full" placeholder="e.g. Printer Paper" value={itemForm.name} onChange={e => setItemForm(f => ({ ...f, name: e.target.value }))} />
              </div>
              <div className="col-span-2">
                <label className="block text-sm font-medium text-surface-700 mb-1">Category</label>
                <select className="select-field w-full mb-2" value={itemForm.category} onChange={e => setItemForm(f => ({ ...f, category: e.target.value }))}>
                  <option value="">Select category</option>
                  {categories.map(c => <option key={c} value={c}>{c}</option>)}
                </select>
                <div className="flex gap-2">
                  <input
                    className="input-field flex-1"
                    placeholder="New category name..."
                    value={newCategory}
                    onChange={e => setNewCategory(e.target.value)}
                    onKeyDown={e => e.key === 'Enter' && (e.preventDefault(), addCategory())}
                  />
                  <button type="button" onClick={addCategory} className="btn-secondary px-4 flex-shrink-0" title="Add category">
                    <Plus className="w-4 h-4" />
                    <span className="ml-1 hidden sm:inline">Add</span>
                  </button>
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-surface-700 mb-1">Unit</label>
                <select className="select-field w-full" value={itemForm.unit} onChange={e => setItemForm(f => ({ ...f, unit: e.target.value }))}>
                  {UNITS.map(u => <option key={u} value={u}>{u}</option>)}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-surface-700 mb-1">Current Quantity</label>
                <input type="number" min="0" className="input-field w-full" value={itemForm.quantity} onChange={e => setItemForm(f => ({ ...f, quantity: e.target.value }))} />
              </div>
              <div>
                <label className="block text-sm font-medium text-surface-700 mb-1">
                  Minimum Quantity
                  <span className="ml-1.5 text-xs text-surface-400 font-normal">(triggers alert)</span>
                </label>
                <input type="number" min="0" className="input-field w-full" value={itemForm.minimumQuantity} onChange={e => setItemForm(f => ({ ...f, minimumQuantity: e.target.value }))} />
              </div>
              {itemForm.unit === 'pcs' && (
                <div className="col-span-2 p-3 bg-brand-50/50 rounded-lg border border-brand-200">
                  <label className="block text-sm font-medium text-brand-700 mb-2">
                    Bucket Size (optional)
                    <span className="ml-1.5 text-xs text-surface-500 font-normal">(for auto-open in recipes)</span>
                  </label>
                  <div className="flex gap-3">
                    <input
                      type="number"
                      min="0"
                      step="0.1"
                      className="input-field flex-1"
                      placeholder="e.g. 5"
                      value={itemForm.bucketSize}
                      onChange={e => setItemForm(f => ({ ...f, bucketSize: e.target.value }))}
                    />
                    <select
                      className="select-field w-24"
                      value={itemForm.bucketSizeUnit}
                      onChange={e => setItemForm(f => ({ ...f, bucketSizeUnit: e.target.value }))}
                    >
                      <option value="g">g</option>
                      <option value="kg">kg</option>
                      <option value="ml">ml</option>
                      <option value="L">L</option>
                    </select>
                  </div>
                </div>
              )}
              <div className="col-span-2">
                <label className="block text-sm font-medium text-surface-700 mb-1">SKU / Code <span className="text-surface-400 font-normal">(optional)</span></label>
                <input className="input-field w-full" placeholder="e.g. PPR-A4-80G" value={itemForm.sku} onChange={e => setItemForm(f => ({ ...f, sku: e.target.value }))} />
              </div>
              <div className="col-span-2">
                <label className="block text-sm font-medium text-surface-700 mb-1">Description <span className="text-surface-400 font-normal">(optional)</span></label>
                <textarea className="textarea-field w-full" rows={2} placeholder="Brief description..." value={itemForm.description} onChange={e => setItemForm(f => ({ ...f, description: e.target.value }))} />
              </div>
            </div>
            <div className="flex justify-end gap-3 pt-2 border-t border-surface-100">
              <button onClick={() => setItemModal(null)} className="btn-secondary">Cancel</button>
              <button onClick={saveItem} disabled={savingItem} className="btn-primary">
                {savingItem ? 'Saving...' : itemModal === 'add' ? 'Add Item' : 'Save Changes'}
              </button>
            </div>
          </div>
        </Modal>
      )}

      {/* ── Adjust Quantity Modal ── */}
      {adjustModal && (
        <Modal open={true} onClose={() => setAdjustModal(null)} title={`Update Stock: ${adjustModal.name}`}>
          <div className="space-y-4">
            <p className="text-sm text-surface-500">Current stock: <strong>{adjustModal.quantity} {adjustModal.unit}</strong>{adjustModal.minimumQuantity > 0 ? ` · Minimum: ${adjustModal.minimumQuantity} ${adjustModal.unit}` : ''}</p>
            <div>
              <label className="block text-sm font-medium text-surface-700 mb-2">Adjustment type</label>
              <div className="flex gap-2">
                {(canManage ? [
                  { id: 'set', label: 'Set to exact value' },
                  { id: 'add', label: 'Add stock' },
                  { id: 'subtract', label: 'Remove stock' },
                ] : [
                  { id: 'add', label: 'Add stock' },
                  { id: 'subtract', label: 'Remove stock' },
                ]).map(m => (
                  <button
                    key={m.id}
                    onClick={() => { setAdjustMode(m.id); setAdjustQty(m.id === 'set' ? adjustModal.quantity : 0); }}
                    className={cn('flex-1 py-2 px-3 rounded-lg border text-sm font-medium transition-colors', adjustMode === m.id ? 'bg-brand-50 border-brand-300 text-brand-700' : 'border-surface-200 text-surface-600 hover:border-surface-300')}
                  >
                    {m.label}
                  </button>
                ))}
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium text-surface-700 mb-1">
                {adjustMode === 'set' ? 'New quantity' : adjustMode === 'add' ? 'Quantity to add' : 'Quantity to remove'}
              </label>
              <input
                type="number" min="0" className="input-field w-full text-lg"
                value={adjustQty}
                onChange={e => setAdjustQty(e.target.value)}
              />
              {adjustMode !== 'set' && (
                <p className="text-xs text-surface-400 mt-1">
                  Result: {adjustMode === 'add' ? adjustModal.quantity + Number(adjustQty) : Math.max(0, adjustModal.quantity - Number(adjustQty))} {adjustModal.unit}
                </p>
              )}
            </div>
            <div className="flex justify-end gap-3 pt-2 border-t border-surface-100">
              <button onClick={() => setAdjustModal(null)} className="btn-secondary">Cancel</button>
              <button onClick={saveAdjust} disabled={savingAdjust} className="btn-primary">
                {savingAdjust ? 'Saving...' : 'Update Stock'}
              </button>
            </div>
          </div>
        </Modal>
      )}

      {/* ── Request Item Modal ── */}
      {requestModal && (
        <Modal open={true} onClose={() => setRequestModal(false)} title="Request Item">
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-surface-700 mb-1">Item Name *</label>
              {requestForm.itemId ? (
                <div className="flex items-center gap-2">
                  <input className="input-field flex-1" value={requestForm.itemName} readOnly />
                  <button onClick={() => setRequestForm(f => ({ ...f, itemId: '', itemName: '' }))} className="btn-ghost p-2 rounded-lg text-surface-400">×</button>
                </div>
              ) : (
                <>
                  <input className="input-field w-full" placeholder="Type item name..." value={requestForm.itemName} onChange={e => setRequestForm(f => ({ ...f, itemName: e.target.value }))} />
                  {items.length > 0 && requestForm.itemName && (
                    <div className="mt-1 border border-surface-200 rounded-lg overflow-hidden shadow-sm max-h-36 overflow-y-auto">
                      {items.filter(i => i.name.toLowerCase().includes(requestForm.itemName.toLowerCase())).slice(0, 5).map(i => (
                        <button key={i.id} onClick={() => setRequestForm(f => ({ ...f, itemId: i.id, itemName: i.name }))} className="w-full text-left px-3 py-2 text-sm hover:bg-surface-50 flex items-center justify-between">
                          <span>{i.name}</span>
                          <StockBadge item={i} />
                        </button>
                      ))}
                    </div>
                  )}
                </>
              )}
            </div>
            <div>
              <label className="block text-sm font-medium text-surface-700 mb-1">Quantity *</label>
              <input type="number" min="1" className="input-field w-full" value={requestForm.quantity} onChange={e => setRequestForm(f => ({ ...f, quantity: e.target.value }))} />
            </div>
            <div>
              <label className="block text-sm font-medium text-surface-700 mb-1">Reason *</label>
              <textarea className="textarea-field w-full" rows={3} placeholder="Why is this item needed?" value={requestForm.reason} onChange={e => setRequestForm(f => ({ ...f, reason: e.target.value }))} />
            </div>
            <label className="flex items-center gap-3 cursor-pointer">
              <div
                onClick={() => setRequestForm(f => ({ ...f, urgent: !f.urgent }))}
                className={cn('w-10 h-6 rounded-full transition-colors flex items-center px-0.5', requestForm.urgent ? 'bg-orange-500' : 'bg-surface-200')}
              >
                <div className={cn('w-5 h-5 rounded-full bg-white shadow transition-transform', requestForm.urgent ? 'translate-x-4' : 'translate-x-0')} />
              </div>
              <span className="text-sm font-medium text-surface-700">Mark as urgent</span>
            </label>
            <div className="flex justify-end gap-3 pt-2 border-t border-surface-100">
              <button onClick={() => setRequestModal(false)} className="btn-secondary">Cancel</button>
              <button onClick={submitRequest} disabled={savingRequest} className="btn-primary">
                {savingRequest ? 'Submitting...' : 'Submit Request'}
              </button>
            </div>
          </div>
        </Modal>
      )}

      {/* ── Review Request Modal ── */}
      {reviewModal && (
        <Modal open={true} onClose={() => setReviewModal(null)} title="Review Stock Request">
          <div className="space-y-4">
            <div className="bg-surface-50 rounded-xl p-4 space-y-1.5">
              <div className="flex items-center gap-2">
                <p className="font-semibold text-surface-900">{reviewModal.itemName}</p>
                {reviewModal.urgent && <span className="text-xs px-1.5 py-0.5 rounded bg-orange-100 text-orange-700 font-medium">URGENT</span>}
              </div>
              <p className="text-sm text-surface-600">Qty: <strong>{reviewModal.quantity}</strong> · Requested by: <strong>{reviewModal.requestedByName}</strong></p>
              <p className="text-sm text-surface-600">"{reviewModal.reason}"</p>
            </div>
            <div>
              <label className="block text-sm font-medium text-surface-700 mb-1">Notes <span className="text-surface-400 font-normal">(optional)</span></label>
              <textarea className="textarea-field w-full" rows={2} placeholder="Add a note for the requester..." value={reviewNotes} onChange={e => setReviewNotes(e.target.value)} />
            </div>
            <div className="flex justify-end gap-2 pt-2 border-t border-surface-100">
              <button onClick={() => setReviewModal(null)} className="btn-secondary">Cancel</button>
              {reviewModal.status === 'pending' && (
                <>
                  <button onClick={() => handleReview('rejected')} disabled={savingReview} className="btn-danger flex items-center gap-1.5">
                    <XCircle className="w-4 h-4" /> Reject
                  </button>
                  <button onClick={() => handleReview('approved')} disabled={savingReview} className="btn-primary flex items-center gap-1.5">
                    <CheckCircle className="w-4 h-4" /> Approve
                  </button>
                </>
              )}
              {reviewModal.status === 'approved' && (
                <button onClick={() => handleReview('fulfilled')} disabled={savingReview} className="btn-primary flex items-center gap-1.5 bg-emerald-600 hover:bg-emerald-700">
                  <CheckCircle className="w-4 h-4" /> Mark as Fulfilled
                </button>
              )}
            </div>
          </div>
        </Modal>
      )}

      {/* ── Delete Confirm Modal ── */}
      {deleteConfirm && (
        <Modal open={true} onClose={() => setDeleteConfirm(null)} title="Delete Item">
          <div className="space-y-4">
            <p className="text-surface-600">Are you sure you want to remove <strong>{deleteConfirm.name}</strong> from stock? This cannot be undone.</p>
            <div className="flex justify-end gap-3 pt-2 border-t border-surface-100">
              <button onClick={() => setDeleteConfirm(null)} className="btn-secondary">Cancel</button>
              <button onClick={confirmDelete} className="btn-danger">Delete Item</button>
            </div>
          </div>
        </Modal>
      )}

      {/* ── Open Unit Modal ── */}
      <Modal open={!!openUnitModal} onClose={() => setOpenUnitModal(null)} title={openUnitModal ? `Open: ${openUnitModal.name}` : ''} size="sm">
        <div className="space-y-4">
          <p className="text-sm text-surface-500">Opening 1 {openUnitModal?.unit || 'unit'}. Optionally set the total capacity to track its fill level as you use it.</p>
          <div>
            <label className="label">Total capacity (when full)</label>
            <div className="flex gap-2">
              <input
                type="number" min="0" step="any"
                className="input-field flex-1"
                placeholder="e.g. 5000"
                value={openUnitForm.capacity}
                onChange={e => setOpenUnitForm(f => ({ ...f, capacity: e.target.value }))}
              />
              <select
                className="select-field w-20"
                value={openUnitForm.levelUnit}
                onChange={e => setOpenUnitForm(f => ({ ...f, levelUnit: e.target.value }))}
              >
                {['g', 'kg', 'ml', 'L', 'pcs', 'oz', 'lb'].map(u => <option key={u} value={u}>{u}</option>)}
              </select>
            </div>
            <p className="text-[11px] text-surface-400 mt-1">Leave empty if you don't need level tracking for this item.</p>
          </div>
          <div className="flex gap-2 pt-2 border-t border-surface-100">
            <button onClick={() => setOpenUnitModal(null)} className="btn-secondary flex-1">Cancel</button>
            <button onClick={confirmOpenUnit} disabled={openingUnit} className="btn-primary flex-1">
              {openingUnit ? 'Opening…' : 'Open unit'}
            </button>
          </div>
        </div>
      </Modal>

      {/* ── Level Edit Modal ── */}
      <Modal open={!!levelEditModal} onClose={() => setLevelEditModal(null)} title="Adjust fill level" size="sm">
        {levelEditModal && (
          <div className="space-y-4">
            <div className="flex items-center gap-3 p-3 rounded-xl bg-sky-50 border border-sky-200">
              <PackageOpen className="w-5 h-5 text-sky-600 flex-shrink-0" />
              <div className="min-w-0">
                <p className="text-sm font-semibold text-surface-900">{levelEditModal.item.name} — Unit #{levelEditModal.entryIdx + 1}</p>
                <p className="text-[11px] text-sky-600">
                  Capacity: {levelEditModal.entry.capacity} {levelEditModal.entry.levelUnit || ''} · Opened {formatOpenedAt(levelEditModal.entry.at)}
                </p>
              </div>
            </div>
            <div>
              <label className="label">Current level</label>
              <div className="flex items-center gap-2">
                <input
                  type="range" min="0" max={levelEditModal.entry.capacity || 100} step="1"
                  value={levelEditValue}
                  onChange={e => setLevelEditValue(e.target.value)}
                  className="flex-1 accent-sky-500"
                />
                <input
                  type="number" min="0" max={levelEditModal.entry.capacity || 99999} step="any"
                  value={levelEditValue}
                  onChange={e => setLevelEditValue(e.target.value)}
                  className="input-field w-20 text-sm"
                />
                <span className="text-xs text-surface-500">{levelEditModal.entry.levelUnit || ''}</span>
              </div>
              {levelEditModal.entry.capacity > 0 && (
                <div className="h-2 rounded-full bg-surface-100 overflow-hidden mt-2">
                  <div
                    className={cn(
                      'h-full rounded-full transition-all',
                      (Number(levelEditValue) / levelEditModal.entry.capacity) < 0.15 ? 'bg-red-500' :
                      (Number(levelEditValue) / levelEditModal.entry.capacity) < 0.4 ? 'bg-amber-500' : 'bg-sky-500'
                    )}
                    style={{ width: `${Math.min(100, (Number(levelEditValue) / levelEditModal.entry.capacity) * 100)}%` }}
                  />
                </div>
              )}
            </div>
            <div className="flex gap-2 pt-2 border-t border-surface-100">
              <button onClick={() => setLevelEditModal(null)} className="btn-secondary flex-1">Cancel</button>
              <button onClick={saveLevelEdit} className="btn-primary flex-1">Save level</button>
            </div>
          </div>
        )}
      </Modal>
    </Layout>
  );
}
